go.mod, go.sum, off-chain/config/config.go, off-chain/scan/browsersync/goerli/goerliEventLogScan.go, off-chain/scan/browsersync/polygon/polygonEventLogScan.go
fix can not read new log problem
=> Cannotrednewlog

off-chain/database/database.go, off-chain/scan/browsersync/goerli/goerliEventLogService.go, off-chain/scan/browsersync/polygon/polygonEventLogService.go
=> change fatal to error

blockchain/browsersync/nbai/nbaiEventLogScan.go, config/config.go, config/config.toml.example, main/payment-bridge.go
scan 2000 or others number  every time in nbai blockchain
Specify cycle interval time
=> change to scan 2000 blocks every time in nbai blockchain

blockchain/browsersync/goerli/goerliEventLogScan.go, blockchain/browsersync/nbai/nbaiEventLogScan.go, blockchain/browsersync/polygon/polygonEventLogScan.go, config/config.go, config/config.toml.example, main/payment-bridge.go
change polygon&goerli scan 2000 block everytime
=> Polygon golier2000

config/config.toml.example
add chainID config parameter for bsc to config.toml.example
=> modify config.toml.example

blockchain/browsersync/bsc/bscEventLogScan.go, blockchain/browsersync/goerli/goerliEventLogScan.go, blockchain/browsersync/nbai/nbaiEventLogScan.go, blockchain/browsersync/polygon/polygonEventLogScan.go, blockchain/scanFactory/scanFactory.go, main/payment-bridge.go
change scan part to Factory mode
=> change scan part to Factory mode

models/EventPolygon.go
modify lock_tx_hash t0 lock_tx_status in event_polygon modle
=> modify lock_tx_hash t0 lock_tx_status in event_polygon modle

on-chain/contracts/FilswanOracle.sol, on-chain/contracts/SwanPayment.sol, on-chain/contracts/abi/FilswanOracle.json, on-chain/hardhat.config.js, on-chain/scripts/upgrade-dao.js
1. add unlockpayment event
2. remove 'term' field from both signTransaction call and event
3. add getThreshold function
4. generate new FilswanOracle abi file
=> Upgrade dao

routers/billing/billing_service.go
billing history order by lock time desc
=> billing history order by lock time desc

scheduler/scanDealStatusAndSaveToDB.go, scheduler/unlockpamentbydao.go
=> modify log info in scheduler

routers/storage/storageRouter.go
=> return total dao number

blockchain/browsersync/scanlockpayment/polygon/polygonEventLogScan.go, routers/storage/storageRouter.go
add unlock status to detail page
start to run scanning sao event
=> start to run scanning sao event

routers/storage/storageRouter.go
=> fix bug : pagenation not work

routers/storage/storageRouter.go, routers/storage/storageService.go
The total number of rows in the query is incorrect
=> Pagenation

models/EventUnlockPayment.go, scheduler/unlockpamentbydao.go
=> fix bug: update unlock info is not right

blockchain/browsersync/scanlockpayment/polygon/polygonScanEventLockPaymentService.go
change lock payment status from paid to processing when scaned event
=> change lock payment status from paid to processing when scaned event

common/utils/utils.go, models/DealFile.go, models/SourceFileDealFileMap.go, routers/storage/storageService.go, scheduler/createtask.go, scheduler/senddeal.go
fix bug: duplicated payload cid to create task
=> fix bug: duplicated payload cid to create task

scheduler/createtask.go
fix bug: duplicated payload cid
=> fix bug: duplicated payload cid

routers/storage/storageService.go
give is_deleted a default value
=> Is deleted

routers/billing/billingDomain.go, routers/billing/billingRouter.go, routers/billing/billingService.go, routers/storage/storageDomain.go, routers/storage/storageRouter.go, routers/storage/storageService.go
show file name in billing history
show file name and ipfs_url in detail
=> to show more info

README.md, script/dbschema.sql
modify readme
add db schema ddl script
=> modify readme

routers/billing/billingService.go
add order by lock payment time in billing history
=> add order by lock payment time in billing history

models/SourceFile.go, routers/storage/storageRouter.go, routers/storage/storageService.go
change authorization from jtw token to wallet
=> change authorization from jtw token to wallet

.vscode/launch.json, go.mod, go.sum, main.go, routers/storage/storageService.go, scheduler/createtask.go, scheduler/senddeal.go
- create car files in mcp by calling swan client api
- create public auto-bid task in mcp by using swan client api
- upload car files in mcp by calling swan client api
=> Adapt to new swan-client

common/errorinfo/ErrorCodeAndMsg.go, routers/billing/billingRouter.go, routers/common/commonRouter.go, routers/storage/storageRouter.go
- MCP - NFT - GET API for file payment info/status
- Remove jwt token check in main branch of MCP
=> Remove Authorization and add token_type in GET response

routers/storage/storageRouter.go
- Remove GetDealListFromSwan function
=> Remove GetDealListFromSwan function

models/EventLockPayment.go, routers/billing/billingService.go, scheduler/scanDealStatusAndSaveToDB.go
=> Add refund function(Update)

go.mod, go.sum, main.go, models/SourceFile.go, routers/storage/storageRouter.go, routers/storage/storageService.go, scheduler/common.go, scheduler/create_task.go, scheduler/scan_deal.go, scheduler/send_deal.go
create car file, upload car file, create task
get source file list
=> merge file

models/SourceFile.go, routers/storage/storageDomain.go, routers/storage/storageService.go
- Modify Dao Signature for new contract
=> Modify Dao Signature for new contract

common/errorinfo/ErrorCodeAndMsg.go, routers/billing/billingService.go, routers/storage/storageDomain.go, routers/storage/storageRouter.go, routers/storage/storageService.go
Reverts filswan/multi-chain-payment#170
=> Revert "Fixing issue with Dao"

routers/storage/storageService.go
- Fixing SQL to extract available deal to sign
=> Fixing DAO issue

models/coin.go, models/eth_type.go, on-chain/client/common.go, on-chain/client/dao.go, on-chain/client/price.go, routers/storage/domain.go, routers/storage/router.go, routers/storage/service.go, scheduler/unlock_pament.go
=> Modify event_dao_signature

routers/storage/domain.go, routers/storage/service.go
=> Add filename to api

README.md, go.mod, main.go, on-chain/client/price.go, on-chain/client/unlock_payment.go, scheduler/common.go, scheduler/create_task.go, scheduler/scan_deal.go, scheduler/send_deal.go, scheduler/unlock_payment.go
optimize merge to car file step
fixed bug when computing max price
optimize create scheduler job
fixed bug when for set unlock payment info
=> fixed bug & optimize

config/config.go, config/config.toml.example, models/deal_file.go, models/source_file.go, scheduler/common.go, scheduler/create_task.go, scheduler/refund.go, scheduler/unlock_payment.go
=> refactor, separate refund from unlock
